version: 0.2

phases:
  install:
    commands:
      - echo "Installing SonarQube Scanner..."
      - wget -qO /tmp/sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"
      - unzip -q /tmp/sonar-scanner.zip -d /tmp
      - echo "Fetching secrets from Secrets Manager..."
      - SONARQUBE_URL=$(aws secretsmanager get-secret-value --secret-id prod/sonar --query SecretString --output text | jq -r '.HOST')
      - SONARQUBE_TOKEN=$(aws secretsmanager get-secret-value --secret-id SonarQubeCredentials --query SecretString --output text | jq -r '.sonartoken')
  build:
    commands:
      - echo "Running SonarQube Scan..."
      - /tmp/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.projectKey=[your_project_key] -Dsonar.sources=. -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN
  post_build:
    commands:
      - echo "SonarQube analysis completed"

artifacts:
  files:
    - '**/*'